services:
  - type: web
    name: khushi-optics-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: "*"
